### ISSUE TITLE
Doc Update: JS Remoting in Visualforce

### ISSUE THREAD

**Issue by toddhalfpenny** [forcedotcom/SalesforceMobileSDK-Shared#245]
In the documentation for _JavaScript Remoting in Visualforce_ there is the section for refreshing the access token. There is currently the lines as follows;
```
// Refresh CSRF cookie
<provider>.refresh(function() {
<Retry call for a seamless user experience>;
});
```

This could do with improving with some example code as trying to find out what `<provider>` should be is very tricky. The following would be beneficial I think (and note the extra line that we are using to make this work robustly).
```
Visualforce.remoting.oauthAccessToken = creds.accessToken;

// Refresh CSRF cookie
// note <provider> can be accessed via the following;
// var providers = Visualforce.remoting.Manager.providers;  // array of providers
// var provider = Visualforce.remoting.last;    // last provider in the array (usually just one available)
<provider>.refresh(function() {
<Retry call for a seamless user experience>;
});
```

**Comment by wmathurin** [comment]
@rwhitley Has the doc been updated?

**Comment by rwhitley** [comment]
Yes. It now says this:

Do something like this:

// Refresh oauth token
cordova.require("com.salesforce.plugin.oauth").authenticate(
  function(creds) {
    // Reload hidden iframe that points to a blank page to
    // to refresh Visualforce domain cookies
    var iframe = document.getElementById("blankIframeId");
    iframe.src = src;
    // Refresh CSRF cookie
    // Get the provider array
    var providers = Visualforce.remoting.Manager.providers;
    // Get the last provider in the arrays (usually only one)
    var provider = Visualforce.remoting.last;
    provider.refresh(function() {
      //Retry call for a seamless user experience
    });
  },
  function(error) {
    console.log("Refresh failed");
  }
);

On Tue, Aug 18, 2015 at 11:26 AM, Wolfgang Mathurin <
notifications@github.com> wrote:

> @rwhitley <https://github.com/rwhitley> Has the doc been updated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/SalesforceMobileSDK-Shared/issues/245#issuecomment-132308199>
> .
>



-- 
Richard

**Comment by wmathurin** [comment]
Thanks @rwhitley
