### ISSUE TITLE
/libs/cordova.force.js exposing an inexistent syncUp signature in Android.

### ISSUE THREAD

**Issue by Entamut** [forcedotcom/SalesforceMobileSDK-Shared#308]
Hi,

Maybe I'm wrong, but I think syncUp signature (cordova.force.js line 892) is exposing a non-implemented method in Android plugin:
function(isGlobalStore, target, soupName, options, successCB, errorCB)

If you check "SalesforceMobileSDK-Android/libs/SmartSync/src/com/salesforce/androidsdk/smartsync/manager/SyncManager.java" it seems there is no "success/error" approach. It's all about one Callback (the one related to "sync" event).

I can't match cordova.force.js function with its counterpart at SmartSync project for Android. So either cordova.force.js is wrong (errorCB will never be called by Android code) or Android plugin should implement the "sucess/error" approach.

I found my successCB is called only at the beginning of the syncUp process. That's fine, but it only helps on knowing when the process is starting. Listening to "sync" event (as documentation says) is fine, but sync happens not only when "smartsyncing" but also when fetching collections. Why not firing an "smartsync" event instead of using the same "sync" event? That's confusing.

Thanks.

**Comment by wmathurin** [comment]
Actually look at https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/master/libs/SalesforceHybrid/src/com/salesforce/androidsdk/phonegap/plugin/SmartSyncPlugin.java line 100.
If something bad happens when starting the sync up, the error callback will be invoked.
If the sync up gets started, and it later hits a problem, then the problem will be relayed back through an event with sync status of failed.

**Comment by Entamut** [comment]
I'm pointing to SyncManager.java. I think you're looking to the wrong class.
Please, do the test:
1) Prepare a sync object (using field names, and one of them must not exist in Salesforce). This has to be done in JS
2) Call SyncUp from JS

You will get no errors at all, but if you debug the execution you will find Salesforce API tells you about an non existent field in your object request.
That won't produce a JSONException or whatever exception. That's fine because is a "syntax error" somehow. But you will never notice because SyncManager will tell you nothing about it.

Main issue is there is no way Java side could call JS callbackonerror.
AFAIK this Git issue should be still open.

**Comment by wmathurin** [comment]
Sync are asynchronous - the cordova call will return without waiting for the sync to complete.
See also my comment here: https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/956#issuecomment-292361590
