### ISSUE TITLE
Issue with Sample Userlist hybrid app 

### ISSUE THREAD

**Issue by AnchalBhardwaj** [forcedotcom/SalesforceMobileSDK-Shared#352]
I followed the steps given in document https://developer.salesforce.com/docs/atlas.en-us.mobile_sdk.meta/mobile_sdk/hybrid_samples_build.htm to get started with Hybrid Adroid App

As mentioned after running cordova prepare in command line, I load the platform/android project in android studio and click on run, it throws below error: 

- 05-01 02:04:40.112 5340-5340/com.salesforce.trailhead I/chromium: [INFO:CONSOLE(59)] "Uncaught module com.salesforce.plugin.oauth not found", source: file:///android_asset/www/cordova.js (59)
- 05-01 02:04:40.121 5340-5417/com.salesforce.trailhead E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000b44
- 05-01 02:04:40.129 5340-5417/com.salesforce.trailhead E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000bd0
- 05-01 02:04:40.289 5340-5417/com.salesforce.trailhead E/eglCodecCommon: **** ERROR unknown type 0x0 (glSizeof,72)
- 05-01 02:04:40.289 5340-5417/com.salesforce.trailhead E/eglCodecCommon: **** ERROR unknown type 0x0 (glSizeof,72)
- 05-01 02:04:40.298 5340-5417/com.salesforce.trailhead E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000b44
- 05-01 02:04:40.312 5340-5417/com.salesforce.trailhead E/eglCodecCommon: glUtilsParamSize: unknow param 0x00000bd0
- 05-01 02:04:40.333 5340-5417/com.salesforce.trailhead E/eglCodecCommon: **** ERROR unknown type 0x0 (glSizeof,72)
- 05-01 02:04:40.333 5340-5417/com.salesforce.trailhead E/eglCodecCommon: **** ERROR unknown type 0x0 (glSizeof,72)

Am not able to procedd after this. I had tried multiple suggestions given in other forums but nothing seems to work. Including the below one: 

- Create a local directory.
- npm install forcedroid
- npm install shelljs
- Use node_modules/.bin/forcedroid to generate an app.
- Follow the output instructions at the end of the script to import the app into Android Studio.
- Compile and launch the app.

**Comment by wmathurin** [comment]
The warnings you pasted above are unrelated to the Mobile SDK and happen in all emulators when you have use host GPU enabled. See http://stackoverflow.com/questions/28966496/android-studio-emulator-eglsurfaceattrib-not-implemented

If the application is not working - do you see other errors in the log (or when you ran forcedroid)?

**Comment by AnchalBhardwaj** [comment]
Yes, I still see **"Uncaught module com.salesforce.plugin.oauth not found", source: file:///android_asset/www/cordova.js (59) error" **while running it through android studio.

**Comment by AnchalBhardwaj** [comment]
While creating forcedroid project, I get "SENDER_ID error". After going through the docs, executed below commands in the given sequence

- cordova plugin add phonegap-plugin-push --variable SENDER_ID="3456789" - It gives a result saying AndroidManifest.xml file for Salesforce SDk plugin. 
- cordova plugin add https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin

After the above steps, Import the android directory of the cordova project into android studio. Build Menu > Clean Project. 

It gives error "Unfortubately, Launcher3 has stopped working" and then it just stops.

**Comment by huminzhi** [comment]
Could be same issue as https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1111? We have a fix of it and will release it soon
