### ISSUE TITLE
force.js apis - queryAll & queryMore

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-Shared#516]
Hello,

As we are updating the SDK in our app to the latest version, I found below issues in force.js file -

1. The queryAll api call is not available. Can we add that in force.js or do we have any alternate here?
2. In queryMore has a typo [here](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/c12cbac3b1c21258dcf766fc224c937c7b0ee22b/libs/force.js#L688). It should be `obj.params` not `obj.parans`

Please help.

**Comment by wmathurin** [comment]
Thanks for reporting.
Both issues will be fixed in the next release (see https://github.com/forcedotcom/SalesforceMobileSDK-Shared/pull/517).
In the meantime, you can simply pull the updated force.js into your application.
