### ISSUE TITLE
parseUrl from queryMore

### ISSUE THREAD

**Issue by akshayajeevan** [forcedotcom/SalesforceMobileSDK-Shared#518]
Hi,

As we have large no of records for few objects, we needs to use `queryMore(url, successHandler, errorHandler)` where the url is `nextRecordsUrl` from `query` response. This url starts with `"/services/data/..."`. 
Now the regular expression present `parseUrl` method is matching when the above url starts with `instanceUrl (https://test.salesforce.com)`. Due to this we have to add our `instanceUrl` to the `nextRecordsUrl` before calling `queryMore` method.

Can we modify the RegEx groups ([here](https://github.com/forcedotcom/SalesforceMobileSDK-Shared/blob/c12cbac3b1c21258dcf766fc224c937c7b0ee22b/libs/force.js#L144)) so that it can parse url which doesn't starts with the app's instance? 

Please help.

**Comment by wmathurin** [comment]
Fix coming to our next release (8.2). See https://github.com/forcedotcom/SalesforceMobileSDK-Shared/pull/523
